spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: vets-service
          uri: http://vets-service.default.learning.petclinic.com
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: http://visits-service.default.learning.petclinic.com
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: http://customers-service.default.learning.petclinic.com
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2

    config:
      uri: http://config-server.default.learning.petclinic.com:8888
  application:
    name: api-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server.default.learning.petclinic.com:8761/eureka/
---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      uri: http://config-server:8888
